name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-agenie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Run Format
        run: bun run format

      - name: Run Lint
        run: bun run lint

      - name: Run Typecheck
        run: bun run typecheck
